-- Dedicated schema + role for user auth data — kept separate from the
-- 4 domain roles on purpose. Login API should NOT reuse PARTNER_DOMAIN_ROLE
-- or any other domain role; that would give the login path implicit
-- visibility into domain schemas it has no reason to touch.

CREATE SCHEMA IF NOT EXISTS PARTNER_INTELLIGENCE_DB.USER_DATA;

CREATE TABLE IF NOT EXISTS PARTNER_INTELLIGENCE_DB.USER_DATA.USERS (
    USER_ID       STRING PRIMARY KEY,
    EMAIL         STRING UNIQUE NOT NULL,
    PASSWORD_HASH STRING NOT NULL,
    NAME          STRING,
    ROLES         STRING NOT NULL  -- comma-separated: "partner,market"
);

CREATE ROLE IF NOT EXISTS AUTH_DOMAIN_ROLE;

GRANT USAGE ON DATABASE PARTNER_INTELLIGENCE_DB TO ROLE AUTH_DOMAIN_ROLE;
GRANT USAGE ON SCHEMA PARTNER_INTELLIGENCE_DB.USER_DATA TO ROLE AUTH_DOMAIN_ROLE;
GRANT SELECT ON TABLE PARTNER_INTELLIGENCE_DB.USER_DATA.USERS TO ROLE AUTH_DOMAIN_ROLE;
-- INSERT only if the login API also handles user creation; omit if users
-- are provisioned separately (e.g. by an admin script using a different role)
GRANT INSERT ON TABLE PARTNER_INTELLIGENCE_DB.USER_DATA.USERS TO ROLE AUTH_DOMAIN_ROLE;
GRANT USAGE ON WAREHOUSE <YOUR_WAREHOUSE_NAME> TO ROLE AUTH_DOMAIN_ROLE;

CREATE USER IF NOT EXISTS AUTH_SVC
    RSA_PUBLIC_KEY = ''
    DEFAULT_WAREHOUSE = PARTNER_INTELLIGENCE_WH;
GRANT ROLE AUTH_DOMAIN_ROLE TO USER AUTH_SVC;
